steps:
  # Etapa 1: Instala dependências
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']
    dir: 'frontend'

  # Etapa 2: Build do Next.js
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export NEXT_PUBLIC_API_URL="https://nutriscan-backend-925272362555.southamerica-east1.run.app"
        npm run build
    dir: 'frontend'

  # Etapa 3: Baixa a chave secreta e a salva em um arquivo
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'gcloud secrets versions access latest --secret="FIREBASE_SERVICE_ACCOUNT_KEY" > /workspace/frontend/key.json'
    dir: 'frontend'

  # Etapa 4: Ativa o experimento e faz o deploy usando a chave
  - name: 'node:18'
    env:
      - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/frontend/key.json'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Verificando se o arquivo de credenciais existe..."
        ls -la /workspace/frontend/key.json
        echo "Ativando experimento webframeworks..."
        npx firebase-tools experiments:enable webframeworks
        echo "Iniciando deploy..."
        npx firebase-tools deploy --only hosting --project $PROJECT_ID --non-interactive
    dir: 'frontend'

options:
  logging: CLOUD_LOGGING_ONLY
