steps:
  # Etapa 1: Instala as dependências usando uma imagem do Node.js v18 (LTS)
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']
    dir: 'frontend'

  # Etapa 2: Executa o build usando a mesma imagem do Node.js v18
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'frontend'

  # Etapa 3: Faz o deploy para o Firebase Hosting
  - name: 'us-central1-docker.pkg.dev/firebase-hosting-producers/firebase'
    args:
      - 'deploy'
      - '--only'
      - 'hosting'
      - '--project'
      - '$PROJECT_ID'
      - '--non-interactive'
      - '--token'
      - '$$FIREBASE_TOKEN'
    secretEnv: ['FIREBASE_TOKEN']

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_TOKEN/versions/latest
      env: 'FIREBASE_TOKEN'

options:
  logging: CLOUD_LOGGING_ONLY