steps:
  # Etapa 1: Instala as dependências do Node.js
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'frontend'

  # Etapa 2: Executa o comando de build
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: 'frontend'

  # Etapa 3: Faz o deploy para o Firebase Hosting
  - name: 'gcr.io/firebase/firebase'
    args:
      - 'deploy'
      - '--only'
      - 'hosting'
      - '--project'
      - '$PROJECT_ID'
      - '--non-interactive'
      - '--token'
      - '$$FIREBASE_TOKEN'
    secretEnv: ['FIREBASE_TOKEN']

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_TOKEN/versions/latest
      env: 'FIREBASE_TOKEN'

# Opções para a build (SEÇÃO ADICIONADA)
options:
  logging: CLOUD_LOGGING_ONLY