steps:
  # Etapa 1: Instala dependências
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']
    dir: 'frontend'

  # Etapa 2: Build do Next.js COM A VARIÁVEL DE AMBIENTE DE PRODUÇÃO
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'frontend'
    env:
      - 'NEXT_PUBLIC_API_URL=https://nutriscan-backend-925272362555.southamerica-east1.run.app'

  # Etapa 3: Baixa a chave secreta e a salva em um arquivo
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'gcloud secrets versions access latest --secret="FIREBASE_SERVICE_ACCOUNT_KEY" > key.json'
    dir: 'frontend'

  # Etapa 4: Faz o deploy usando a chave
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export GOOGLE_APPLICATION_CREDENTIALS=key.json && \
        npx firebase-tools deploy --only hosting --project $PROJECT_ID --non-interactive
    dir: 'frontend'

options:
  logging: CLOUD_LOGGING_ONLY
