steps:
  # Etapa 1: Instala as dependências do Node.js
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'frontend' # Adicionado para garantir que rode na pasta certa

  # Etapa 2: Executa o comando de build (que agora também exporta para a pasta 'out')
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: 'frontend' # Adicionado para garantir que rode na pasta certa

  # Etapa 3: Faz o deploy para o Firebase Hosting
  # Usamos um 'passo' especial que já tem as ferramentas do firebase instaladas
  - name: 'gcr.io/firebase/firebase'
    args:
      - 'deploy'
      - '--only'
      - 'hosting'
      - '--project'
      - '$PROJECT_ID'
      - '--non-interactive'
      - '--token'
      - '$$FIREBASE_TOKEN' # Usa o token que pegamos do Secret Manager
    secretEnv: ['FIREBASE_TOKEN'] # Informa que esta etapa precisa da variável de segredo

# AQUI ESTÁ A MÁGICA:
# Disponibiliza o segredo para ser usado durante o build.
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_TOKEN/versions/latest
      env: 'FIREBASE_TOKEN' # Mapeia o segredo para uma variável de ambiente chamada FIREBASE_TOKEN