steps:
  # Etapa 1: Instala as dependências usando uma imagem do Node.js v18
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']
    dir: 'frontend'

  # Etapa 2: Executa o build usando a mesma imagem do Node.js v18
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'frontend'

  # ETAPA 3 (ATUALIZADA): Instala e executa o Firebase Tools diretamente
  - name: 'node:18'
    entrypoint: 'npx' # Usamos npx para executar o pacote sem instalar globalmente
    args:
      - 'firebase-tools' # O pacote a ser executado
      - 'deploy'
      - '--only'
      - 'hosting'
      - '--project'
      - '$PROJECT_ID'
      - '--non-interactive'
      - '--token'
      - '$$FIREBASE_TOKEN'
    secretEnv: ['FIREBASE_TOKEN']
    dir: 'frontend' # Garante que o comando rode na pasta com o firebase.json

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_TOKEN/versions/latest
      env: 'FIREBASE_TOKEN'

options:
  logging: CLOUD_LOGGING_ONLY