steps:
  # Etapa 1: Instala dependências (sem mudança)
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']
    dir: 'frontend'

  # Etapa 2: Build do Next.js (sem mudança)
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'frontend'

  # NOVA ETAPA 3: Baixa a chave secreta e a salva em um arquivo
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'gcloud secrets versions access latest --secret="FIREBASE_SERVICE_ACCOUNT_KEY" > key.json'
    dir: 'frontend'

  # ETAPA 4 ATUALIZADA: Faz o deploy usando a chave, não o token
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export GOOGLE_APPLICATION_CREDENTIALS=key.json && \
        npx firebase-tools deploy --only hosting --project $PROJECT_ID --non-interactive
    dir: 'frontend'

# NÃO PRECISAMOS MAIS DO TOKEN ANTIGO
# As permissões da conta de serviço já dão acesso a este novo segredo.
options:
  logging: CLOUD_LOGGING_ONLY