# Estas são as etapas que o Cloud Build executará, em ordem.
steps:
  # Etapa 1: Constrói a imagem do contêiner.
  # Ele usa o Dockerfile que criamos no passo anterior.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nutriscan-backend:$COMMIT_SHA', '.']

  # Etapa 2: Envia a imagem construída para o Artifact Registry do Google.
  # É como se fosse um "Docker Hub" privado para o seu projeto.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nutriscan-backend:$COMMIT_SHA']

  # Etapa 3: Implanta a imagem no Cloud Run.
  # Esta é a etapa que realmente publica sua aplicação.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'nutriscan-backend' # Este será o nome do seu serviço no Cloud Run.
      - '--image=gcr.io/$PROJECT_ID/nutriscan-backend:$COMMIT_SHA'
      - '--region=us-central1' # IMPORTANTE: Escolha a região mais próxima de você ou de seus usuários. ex: southamerica-east1 (São Paulo)
      - '--platform=managed'
      - '--allow-unauthenticated' # Permite que qualquer pessoa acesse a API. Se for privada, remova esta linha.
      # A linha mágica: conecta o segredo que criamos à sua aplicação como uma variável de ambiente.
      # Seu código Python agora pode ler a variável 'DATABASE_URL' para se conectar ao banco.
      - '--set-secrets=DATABASE_URL=NEON_DB_CONNECTION_STRING:latest'
      - '--quiet'

# Opções para a build
options:
  # Isso define o nível de permissão que o robô do Cloud Build terá.
  logging: CLOUD_LOGGING_ONLY